version: "3.4"

services:
  ros:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: ros
    network_mode: "host"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    privileged: true
    runtime: nvidia
    #ports:
    #  - "2222:22"
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - /home/ares/Projects/ros_ws:/ros_ws


# then to get inside use : sudo docker exec -it ros /bin/bash
# You ALOSO need to execute : xhost +local:docker
# See that to configure Clion : https://www.allaban.me/posts/2020/08/ros2-setup-ide-docker/
# Use ssh root@localhost to connect